import puppeteer from 'puppeteer';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
const ROOT = new URL('../site/', import.meta.url).pathname;
const T = {'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png'};
const srv = createServer(async(rq,rs)=>{try{let p=decodeURIComponent(rq.url.split('?')[0]); if(p==='/')p='/index.html'; const b=await readFile(join(ROOT,p)); rs.writeHead(200,{'content-type':T[extname(p)]||'application/octet-stream'}); rs.end(b);}catch{rs.writeHead(404);rs.end('nf');}});
await new Promise(r=>srv.listen(0,r)); const port=srv.address().port;
const br=await puppeteer.launch({headless:'new',args:['--no-sandbox']});
const pg=await br.newPage(); await pg.setViewport({width:1440,height:900,deviceScaleFactor:1});
await pg.goto(`http://localhost:${port}/`,{waitUntil:'networkidle0'});
await pg.evaluate(()=>{ const i=document.getElementById('intro'); if(i)i.remove(); document.body.classList.add('hero-ready');
  const st=document.createElement('style'); st.textContent='*{animation-timeline:none !important} .reveal,[class*="reveal"],.hero__line,.word,.bento__card,.pcard,.sp,.tcard,.trust__item,.section,[class*="panel"]{opacity:1 !important;transform:none !important;filter:none !important;visibility:visible !important}'; document.head.appendChild(st); });
await new Promise(r=>setTimeout(r,600));
await pg.screenshot({path:'/tmp/bc-forced-desktop.png',fullPage:true});
await pg.setViewport({width:390,height:844,deviceScaleFactor:1});
await new Promise(r=>setTimeout(r,300));
await pg.screenshot({path:'/tmp/bc-forced-mobile.png',fullPage:true});
await br.close(); srv.close(); console.log('done');
